# NeMo GuardRails Configuration for AI Agent Guards Testing
models:
  - type: main
    engine: openai
    model: gpt-4o-mini
  - type: fallback
    engine: openai
    model: gpt-3.5-turbo-instruct

prompts:
  - task: self_check_facts
    content: |
      Check if the following response contains false or fabricated information:

      {{ bot_response }}

      Answer with "yes" if it contains false/fabricated claims, "no" if it's accurate.

rails:
  output:
    flows:
      - self check facts

# Enhanced fact-checking configuration
fact_checking:
  parameters:
    threshold: 0.6
    evidence_required: true
    confidence_threshold: 0.7
    max_claims_per_response: 5
    verification_sources: ["academic", "government", "verified_media"]
    claim_types: ["quantitative", "historical", "scientific", "medical", "geographic"]

# Hallucination detection configuration
hallucination_detection:
  parameters:
    threshold: 0.5
    num_extra_responses: 2
    consistency_threshold: 0.7

# Self-contradiction detection
self_contradiction:
  parameters:
    threshold: 0.6
    num_samples: 3