# NeMo GuardRails Configuration for AI Agent Guards Testing
models:
  - type: main
    engine: openai
    model: gpt-4o-mini
  - type: fallback
    engine: openai
    model: gpt-3.5-turbo-instruct

prompts:
  - task: self_check_facts
    content: |
      You are a fact-checking expert. Analyze the following response for false, fabricated, or unsubstantiated claims:

      {{ bot_response }}

      CRITICAL CHECKS:
      1. Specific statistics or percentages WITHOUT sources (e.g., "87% of cases..." without citation)
      2. Invented data that cannot be verified
      3. False claims about real-world facts
      4. Fabricated numbers, dates, or measurements
      5. Unsupported generalizations presented as facts

      If the response contains ANY of the following, it is FALSE/FABRICATED:
      - Specific percentages without evidence (e.g., "87% of...")
      - Exact numbers that cannot be verified (e.g., "studies show 73%...")
      - Made-up statistics
      - Unverifiable claims stated as facts

      Answer "yes" if it contains false/fabricated/unsourced claims, "no" if accurate.
      Explain what specific claims are problematic and why (lack of evidence, fabricated statistics, etc.).

rails:
  output:
    flows:
      - self check facts

# Enhanced fact-checking configuration
fact_checking:
  parameters:
    threshold: 0.6
    evidence_required: true
    confidence_threshold: 0.7
    max_claims_per_response: 5
    verification_sources: ["academic", "government", "verified_media"]
    claim_types: ["quantitative", "historical", "scientific", "medical", "geographic"]

# Hallucination detection configuration
hallucination_detection:
  parameters:
    threshold: 0.5
    num_extra_responses: 2
    consistency_threshold: 0.7

# Self-contradiction detection
self_contradiction:
  parameters:
    threshold: 0.6
    num_samples: 3