# Streamlit Secrets File
# Add your API keys here for Streamlit Cloud deployment
# This file should NOT be committed to git

# Required API keys
OPENAI_API_KEY = "your_openai_key_here"
TOGETHER_API_KEY = "your_together_key_here"
HF_TOKEN = "your_huggingface_token_here"  # Optional